apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayuda-humanitaria
  namespace: app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ayuda-humanitaria
  template:
    metadata:
      labels:
        app: ayuda-humanitaria
    spec:
      containers:
        - name: ayuda-humanitaria
          image: ghcr.io/yennifer017/ayuda-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: ayuda-config
            - secretRef:
                name: ayuda-secrets

      imagePullSecrets:
        - name: ghcr-secret-hh
