apiVersion: v1
kind: Service
metadata:
  name: ayuda-humanitaria
  namespace: app-prod
spec:
  selector:
    app: ayuda-humanitaria
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
