apiVersion: v1
kind: ConfigMap
metadata:
  name: centro-config
  namespace: app-prod
data:
  SERVER_PORT: "8080"
  DB_HOST: "ss1-orgcentrodb.postgres.database.azure.com"
  DB_NAME: "centro_datos"

  HH_SERVICE_URL: "http://ayuda-humanitaria:8080"

  FRONTEND_ORIGIN: "https://ss1orgfrontend.z9.web.core.windows.net/"

