apiVersion: apps/v1
kind: Deployment
metadata:
  name: centro-datos
  namespace: app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centro-datos
  template:
    metadata:
      labels:
        app: centro-datos
    spec:
      containers:
        - name: centro-datos
          image: ghcr.io/mazhania4/centro-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: centro-config
            - secretRef:
                name: centro-secrets

      imagePullSecrets:
        - name: ghcr-secret
