apiVersion: v1
kind: Service
metadata:
  name: centro-datos
  namespace: app-prod
spec:
  selector:
    app: centro-datos
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
