apiVersion: v1
kind: Secret
metadata:
  name: centro-secrets
  namespace: app-prod
type: Opaque
data:
  DB_USERNAME: ""
  DB_PASSWORD: ""

  JWT_SECRET: ""
  JWT_REFRESH_SECRET: ""

  EMAIL_USERNAME: ""
  EMAIL_PASSWORD: ""
