name: Deploy to k3s

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn -q -DskipTests clean package

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Export IMAGE var
        id: image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          GIT_SHA=$(echo "${{ github.sha }}" | head -c 7)
          IMAGE=ghcr.io/${OWNER}/centro-backend:${GIT_SHA}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "IMAGE=${IMAGE}" >> $GITHUB_OUTPUT


      - name: Build Docker image
        run: |
          docker build -t $IMAGE .

      - name: Debug show image
        run: |
          echo "step output image = ${{ steps.image.outputs.IMAGE }}"
          echo "env IMAGE_NAME = $IMAGE_NAME" || true

      - name: Push Docker image
        run: docker push ${{ steps.image.outputs.IMAGE }}

      #       DESPLIEGUE DENTRO DE LA VM POR SSH
      - name: Deploy to k3s via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE: ${{ steps.image.outputs.IMAGE }}
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "Usando kubeconfig interno del servidor"
            export KUBECONFIG=/home/azureuser/.kube/config

            echo "Actualizando Deployment centro-datos de $IMAGE"

            kubectl set image deployment/centro-datos centro-datos=$IMAGE -n app-prod --record
            kubectl patch deployment centro-datos -n app-prod -p '{"spec":{"template":{"metadata":{"annotations":{"date":"'"$(date +%s)"'"}}}}}'

            echo "pull image and start pods"
            kubectl -n app-prod rollout restart deployment/centro-datos

            echo "Esperando rollout..."
            kubectl rollout status deployment/centro-datos -n app-prod --timeout=120s

            echo "Deployment completado"
